/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/common/AppLayout.vue')['default']
    ConfirmModal: typeof import('./src/components/common/ConfirmModal.vue')['default']
    DataTable: typeof import('./src/components/common/DataTable.vue')['default']
    EditProposalModal: typeof import('./src/components/common/EditProposalModal.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    NotificationContainer: typeof import('./src/components/common/NotificationContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
