services:
  # Backend service (from main project)
  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    environment:
      - APP_ENV=production
    volumes:
      - ../storage:/var/www/html/storage
    networks:
      - app-network

  # Frontend production
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  # Frontend development
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://backend:80
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

