services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/var/www/html
        depends_on:
            - pgvector
        ports:
            - "9009:9000"  # php-fpm port (optional)

    nginx:
        image: nginx:alpine
        volumes:
            - ./:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8088:80"
        depends_on:
            - app

    pgvector:
        image: pgvector/pgvector:pg16
        environment:
            POSTGRES_DB: vectors
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5435:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    pgdata:
        driver: local


