services:
  # Backend Laravel API
  app:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www/html
    env_file:
      - backend/.env
    depends_on:
      pgvector:
        condition: service_healthy
    networks:
      - app-network

  # Queue worker for background jobs
  worker:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    volumes:
      - ./backend:/var/www/html
    env_file:
      - backend/.env
    depends_on:
      pgvector:
        condition: service_healthy
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    networks:
      - app-network

  # Nginx web server
  nginx:
    image: nginx:alpine
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8088:80"
    depends_on:
      - app
    networks:
      - app-network

  # PostgreSQL with pgvector extension
  pgvector:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: vectors
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Frontend Vue.js development server
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8088
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge


